spring:
  application:
    name: "{SPRING_APP_NAME:SpringSecuritySection1}" 
  security:
    user:
      name: "${SPRING_SECURITY_USER_NAME:admin}"
      password: "${SPRING_SECURITY_USER_PASSWORD:password}"
    
server:
  port: "${SERVER_PORT:8080}"
    
logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"    
  level:
    org:
      springframework:
         security: "${SPRING_SECURITY_LOG_LEVEL:TRACE}"
   